#pragma once

/**
 * Entry point for running UI generated by `editor/` on ESP32 (or in browser Simulator).
 *
 * Lets firmware switch between the hand-written counter demo and exported UI.
 */
void app_generated_init(void);

