#pragma once

/**
 * Entry point for running UI generated by `editor/` in simulator/firmware.
 *
 * This keeps `simulator/main.c` simple and lets CMake switch between the
 * hand-written counter demo and the generated UI.
 */
void app_generated_init(void);

